4teamwork/ftw.file

docs/HISTORY.txt
ftw/file/browser/configure.zcml
ftw/file/tests/test_activity.py

ftw.activity 2.x was refactered and has a different implementation of
activity representation.

Only load ftw.activity 1.x representation if ftw.activity 1.x is installed.

---

docs/HISTORY.txt
ftw/file/custom_outputfilter.py
ftw/file/tests/test_outputfilter.py

@jone I adjusted the output filter so it returns the image url correctly when the plone filter already returns a ImageScale as Image.

fix outputfilter so it works with scaled images.

---

docs/HISTORY.txt
ftw/file/resources/uploader.css

Remove animation of the upload icon when replacing a file.
Because I personally do not like the animation and it keeps repeating while just moving the mouse around, which is really strange.
The first impression for me is that it is a bug, therefore I've removed it.

Remove icon effect when replacing file.

---

docs/HISTORY.txt
ftw/file/browser/configure.zcml
ftw/file/browser/file_view.py

By moving the template binding to python code, subclasses can still render the default template conditionally.

Details view: refactor template binding

---

docs/HISTORY.txt
ftw/file/browser/tinymce.py

The problem was that only images were linkable.
/cc @mbaechtold

Fix regression when trying to link files in TinyMCE.

---

docs/HISTORY.txt
ftw/file/viewlets/content_history.pt

Some journalactions are not translated:
~~Image removed~~
This PR will fix this:

Fix journal action translation for files

---

docs/HISTORY.txt
ftw/file/content/file.py
ftw/file/upgrades/20160601223722_set_empty_document_date/upgrade.py

This PR makes the `documentDate` required.
This will solve sorting issues with the plone catalog if no `documentDate` was set.
See issue #64 for more information.
This PR comes up with following changes:
- required `documentDate`
- Upgradestep to set the `documnetDate` to the `creation`-Date if no `documentDate` is set.
There was no need to adjust the template because there where no checks if the `documentDate` is available or not. The utils method https://github.com/4teamwork/ftw.file/blob/master/ftw/file/utils.py#L109 has a fallback. If there was no `documentDate` it returned the current date. So we don't have to adjust anything else.
Before:
----------
After:
-------
closes #64

Make documentDate required.

---

docs/HISTORY.txt
ftw/file/content/file.py
ftw/file/interfaces.py
ftw/file/tests/test_filename.py

Fix security declaration warnings
```
2016-11-21 14:46:53 WARNING SecurityInfo Conflicting security declarations for "getOriginFilename"
2016-11-21 14:46:53 WARNING SecurityInfo Class "File" had conflicting security declarations
2016-11-21 14:46:55 WARNING SecurityInfo Conflicting security declarations for "setFile"
2016-11-21 14:46:55 WARNING SecurityInfo Class "File" had conflicting security declarations
```
- **fix security declaration of getOriginFilename method.**
- **declare security for is_image and getField.**
- **inherit schema from ATContentTypeSchema.**
The ATFileSchema inherits ATContentTypeSchema and adds the "file"
field.
As we do the same it does not make any sense to inherit ATFileSchema
when we are overwriting the "file" field anyway.
- **Eliminate bad security …

Fix security declaration warnings

---

docs/HISTORY.txt
ftw/file/browser/download.py
ftw/file/tests/test_download.py
setup.py

Fixes https://github.com/4teamwork/ftw.file/issues/34
I decided to use a GET parameter because tweaking a header should be an option of the download view and not a different view which does exactly the same as the download view except changing part of a header.

Added option to download file with inline content-disposition header.

---

docs/HISTORY.txt
ftw/file/testing.py
ftw/file/tests/test_download_redirection.py
setup.py

Rewrite download redirection tests using `ftw.testbrowser` and drop dependency on `ftw.testing[splinter]` (which has been removed from `ftw.testing`).
Fixes current test failures.

Rewrite download redirection tests using ftw.testbrowser, drop dependency on ftw.testing[splinter]

---

docs/HISTORY.txt
ftw/file/profiles/default/registry.xml
ftw/file/tests/test_download_redirection.py
ftw/file/upgrades/20171113100333_add_registry_record/registry.xml
ftw/file/upgrades/20171113100333_add_registry_record/upgrade.py
ftw/file/utils.py

This is useful in intranets (having "bumblebee") where all authenticated users can view files. The users must not be redirected to the download view of the file. Instead they should be able to preview the file.

Add option to disable the redirect to the download view.

---

docs/HISTORY.txt
ftw/file/content/file.py
ftw/file/lawgiver.zcml
ftw/file/permissions.zcml
ftw/file/profiles/default/rolemap.xml
ftw/file/tests/test_advanced_edit.py
ftw/file/upgrades/20180830120830_update_rolemap_with_new_permission/rolemap.xml
ftw/file/upgrades/20180830120830_update_rolemap_with_new_permission/upgrade.py

The new permission is used to protect the edit form tab (schemata) for the expiration date and effective date.
This is useful if you want to grant the permission to edit these field to a role without the need to grant "manage content settings" (which would allow the user to edit all the "advanced" fields).

Introduce new permission "ftw.file: Edit date fields".

---

docs/HISTORY.txt
ftw/file/fields.py
ftw/file/tests/test_download.py
ftw/file/tests/test_filename.py

The additional header payload '*=UTF-8' is solving the problem that
umlauts were displayed wrong in MSIE.
Also Tests had to be adapted since they validate the header.

Fix: Add umlaut support for MSIE filedownload

---

ftw/file/fields.py
ftw/file/tests/test_download.py
ftw/file/tests/test_filename.py

Fixes the side-effects introduced in https://github.com/4teamwork/ftw.file/pull/76
IE and Edge require a different disposition than Chrome, Firefox and Safari
so we need to differ them. I implemented that by checking the user agent content
for keywords suggesting that the user downloads with MSIE or Edge.
It is possible that the keywords do not match all the possible user_agent cases. Since
there is an infinite number of possible user agents. I think covering the most common
cases is perfectly fine.
I tested that the filenames having umlauts and empty space (`ÖsFüülç$.docx` and `Ös Fü ülç$.docx`) in the browsers:
- Chrome (73.0.3683.103)
- Firefox (66.0.5)
- Safari (12.0.3)
- Internet Explorer (11.648.17134.0)
- Edge (42.17134.1.0)

Optimize disposition for most used Browsers

---

docs/HISTORY.txt
ftw/file/profiles/default/types/ftw.file.File.xml
ftw/file/upgrades/20191003173301_archetypes_to_dexterity/types/ftw.file.File.xml
ftw/file/upgrades/20191101165228_fix_fti/types/ftw.file.File.xml

The ID (=filename) and the name of the FTI should be the same (convention).  This fixes the wrong name. AFAIK there is no visible negative impact thus no migration is required.

Fix FTI name to be the same as its ID.

---

docs/HISTORY.txt
ftw/file/upgrades/20191003173301_archetypes_to_dexterity/upgrade.py

When an environment variable is set while running the AT to DX migration upgrade step, the content migration itself is not executed. This makes it possible for a policy package to control in what order which types are migrated.
The existing upgrade step is changed so that it imports the generic setup profile even when the skip-migration-env variable is activated.
Before all generic setup changes had to be copied to the policy package, but we want to be able to only install the configuration changes and migrate later without duplicating the settings.

Dexterity migration: import GS profile even when not migrating

---

docs/HISTORY.txt
ftw/file/upgrades/__init__.py

These fields may appear dynamically when the file is a movie and flowplayer is used.

DX migration: ignore flowplayer fields (width and height).

---

docs/HISTORY.txt
ftw/file/configure.zcml
ftw/file/factories.py

so that ftw.file uploads can work in ftw.simplelayout's FileListingBlock.
Part of resolution for https://github.com/4teamwork/izug.organisation/issues/1620

Add a FileUpload adaptor for plone.namedfile

---

docs/HISTORY.txt
ftw/file/upgrades/20160601223722_set_empty_document_date/upgrade.py
ftw/file/upgrades/20180830120830_update_rolemap_with_new_permission/upgrade.py

2 old AT upgrade steps wouldn't run as is in the 2.x code. So we:
1. Skipped the permission update where the permission is no longer in 2.x code
2. where getDocumentDate was not found for some reason, we coded it differently in the upgrade for that field.

Fix upgrade steps that wouldn't run in 2.x codebase

---

docs/HISTORY.txt
ftw/file/handlers.py

When the Plone site is deleted, we do not want to check for protected files. This fixes deleting the Plone site when ftw.file is installed.

Fix deleting Plone site.

---

docs/HISTORY.txt
ftw/file/content/dxfile.py
ftw/file/upgrades/20200120172522_update_mime_type_metadata/upgrade.py

closes https://github.com/4teamwork/izug.organisation/issues/1806

Override content_type method to fix mimetype metadata.

---

docs/HISTORY.txt
ftw/file/browser/download.py
ftw/file/testing.py
ftw/file/tests/test_download.py
ftw/file/tests/test_download_redirection.py
ftw/file/tests/test_outputfilter.py
ftw/file/tests/test_overlay.py
ftw/file/tests/test_utils.py

Problem:
The redirect view did no quote the URL, which leads to a problem setting the location header in plone 5 if the filename contains a Umlaut.
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 170: ordinal not in range(128)
File "ZPublisher/Publish.py", line 138, in publish
request, bind=1)
File "ZPublisher/mapply.py", line 77, in mapply
if debug is not None: return debug(object,args,context)
File "ZPublisher/Publish.py", line 48, in call_object
result=apply(object,args) # Type s<cr> to step into published object.
File "home/zope/eggs/ftw.file-2.2.6-py2.7.egg/ftw/file/browser/download.py", line 127, in __call__
current_url + '/@@download/file/' + filename)
File "ZPublisher/HTTPResponse.py", line 609, in redirect
self.setHeader('Location', location)
File …
```

Fix file redirect view for plone 5

---

docs/HISTORY.txt
ftw/file/browser/upload.py

When uploading files by Drag'n'Drop through Microsoft Edge 44.17763.1.0 the filename was set to the whole path on the original system. Here you can see the change in filename before and after the fix:

Fix filepath used for filename when uploading through microsoft edge

---

docs/HISTORY.txt
ftw/file/configure.zcml
ftw/file/indexer.py

Previously on AT files it was automatically indexted because the field had the same name ("documentDate"). In the dexterity version of ftw.file the field is called "document_date" instead and thus is not automatically indexed.

Add missing dexterity file documentDate indexer

---

docs/HISTORY.txt
ftw/file/custom_outputfilter.py

Scales of dexterity images do not provide `IImageScale` anymore and thus the custom output filter does stuff which it should not. Because this output filter is only meant for ftw.file.Files in the first place we now also check for that and do not process anything if it's not a ftw.file.File.

Fix scale generation of DX Images in TinyMCE

---

docs/HISTORY.txt
ftw/file/browser/download.py
ftw/file/tests/test_download.py
ftw/file/tests/test_filename.py

For some reason, we did not follow rfc6266 for non-microsoft browsers.
The implementation we had for Microsoft browsers was the correct rfc6266
way and thus we use it as default now. See: https://tools.ietf.org/html/rfc6266#section-5
https://extranet.4teamwork.ch/support/basel-landschaft/tracker/189/

Fix comma in filename results in corrupt content-disposition

---

docs/HISTORY.txt
ftw/file/content/dxfile.py
ftw/file/profiles/default/registry.xml
ftw/file/profiles/default_plone5/registry.xml
ftw/file/profiles/uninstall/registry.xml
ftw/file/profiles/uninstall_plone5/registry.xml
ftw/file/tests/test_invalid_mimetypes.py
ftw/file/upgrades/20201105080517_add_invalid_mimetypes_registry_entry/registry.xml
ftw/file/upgrades/20201105080517_add_invalid_mimetypes_registry_entry/upgrade.py

You can configure globally a list of invalid mimetypes.
The system so far just throws a ValueError if violated. 
Next PR.
- Add form validation

Feature: Restrict mimetypes allowed to use with ftw.file.File.

---

ftw/file/content/dxfile.py
ftw/file/tests/test_invalid_mimetypes.py

The message, that the file is already uploaded comes from plone.formwidget.namefile, since plone now temporary stores files uploaded via html form for you, so it can be used after a validation error and does not have to be chosen again.

Raise Invalid from zope.interface in order to have a meaningful error meassge in z3c.form.
